export const VALIDATE_FORM = 'VALIDATE_FORM';
export const VALIDATE_FORM_SUCCESS = 'VALIDATE_FORM_SUCCESS';
export const VALIDATE_FORM_FAIL = 'VALIDATE_FORM_FAIL';

export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';

export const DOWNLOAD_BOOKS = 'DOWNLOAD_BOOKS';
export const DOWNLOAD_BOOKS_SUCCESS = 'DOWNLOAD_BOOKS_SUCCESS';
export const DOWNLOAD_BOOKS_FAIL = 'DOWNLOAD_BOOKS_FAIL';
