export const VALIDATE_FORM = 'VALIDATE_FORM';
export const VALIDATE_FORM_SUCCESS = 'VALIDATE_FORM_SUCCESS';
export const VALIDATE_FORM_FAIL = 'VALIDATE_FORM_FAIL';

export const ADD_BOOK = 'ADD_BOOK';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAIL = 'ADD_BOOK_FAIL';
